<a href="https://colab.research.google.com/github/jaya-shankar/education-impact/blob/master/interpolation_code/mean_yrs_schooling_interpolation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/jaya-shankar/education-impact.git

Cloning into 'education-impact'...
remote: Enumerating objects: 151, done.
remote: Counting objects: 100% (151/151), done.
remote: Compressing objects: 100% (124/124), done.
remote: Total 151 (delta 75), reused 77 (delta 25), pack-reused 0
Receiving objects: 100% (151/151), 1.00 MiB | 17.36 MiB/s, done.
Resolving deltas: 100% (75/75), done.

In [3]:
import pandas as pd

In [5]:

df

                 Country   1960  1961  1962  ...  2012  2013  2014   2015
0            Afghanistan   1.12   NaN   NaN  ...   NaN   NaN   NaN   9.13
1                Albania  13.99   NaN   NaN  ...   NaN   NaN   NaN  20.59
2                Algeria   4.43   NaN   NaN  ...   NaN   NaN   NaN  21.00
3                 Angola   1.50   NaN   NaN  ...   NaN   NaN   NaN   8.11
4    Antigua and Barbuda   0.00   NaN   NaN  ...   NaN   NaN   NaN  21.96
..                   ...    ...   ...   ...  ...   ...   ...   ...    ...
197       Western Sahara   0.00   NaN   NaN  ...   NaN   NaN   NaN   9.21
198                World  10.17   NaN   NaN  ...   NaN   NaN   NaN  17.94
199                Yemen   0.02   NaN   NaN  ...   NaN   NaN   NaN   9.86
200               Zambia   7.52   NaN   NaN  ...   NaN   NaN   NaN  16.00
201             Zimbabwe  10.24   NaN   NaN  ...   NaN   NaN   NaN  19.15

[202 rows x 57 columns]

In [13]:
years = [(y,y+5) for y in range(1960,2011,5)]
datasets = ["15--24","25--34","35--44","45--54","55--64","65--74","75--84","85--94",'95--']

In [18]:
for name in datasets:
  data = pd.read_csv("/content/education-impact/datasets/wcde-"+name+".csv")   
  df = pd.DataFrame(data)
  for r in range(len(df)):
    for s,e in years:
      df.at[r,str(s)] = round(df.iloc[r][str(s)],2)
      df.at[r,str(e)] = round(df.iloc[r][str(e)],2)
      d   = df.iloc[r][str(e)] - df.iloc[r][str(s)]
      inc = d/5
      i=1
      for y in range(s+1,e):
        df.at[r,str(y)] = round(df.iloc[r][str(s)] + inc*i,2)
        i+=1
  df.to_csv("/content/education-impact/datasets/wcde-"+name+".csv", encoding='utf-8', index=False)

df

                 Country  1960  1961  1962  ...   2012   2013   2014   2015
0            Afghanistan  2.10  1.92  1.74  ...   1.05   1.39   1.72   2.06
1                Albania  0.00  0.00  0.00  ...   1.55   1.88   2.22   2.55
2                Algeria  0.00  0.00  0.00  ...   0.35   0.40   0.46   0.52
3                 Angola  0.07  0.07  0.07  ...   0.74   0.91   1.07   1.24
4    Antigua and Barbuda  0.00  0.00  0.00  ...   3.64   5.47   7.29   9.11
..                   ...   ...   ...   ...  ...    ...    ...    ...    ...
197       Western Sahara  0.00  0.00  0.00  ...   3.07   4.61   6.14   7.68
198                World  5.52  5.65  5.78  ...  11.44  11.43  11.43  11.43
199                Yemen  0.49  0.49  0.49  ...   0.47   0.68   0.90   1.11
200               Zambia  0.46  0.47  0.48  ...   2.22   2.47   2.73   2.99
201             Zimbabwe  0.04  0.05  0.05  ...   1.97   2.17   2.36   2.56

[202 rows x 57 columns]